[package]
name = "xdc"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xdc_macros = { path = "../xdc_macros" }
