[package]
name = "xdc"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xdc_macros = { path = "../xdc_macros", default-features = false }
linkme = "0.3" # Re-exported here to ensure downstream users don't need to depend on it

[features]
default = ["std"]
alloc = ["xdc_macros/alloc"]
std = ["alloc", "xdc_macros/std"]